version: '3.8'
services:
  task-manager-api:
    build:
      context: ./task-manager-api
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    volumes:
      - .:/app
    environment:
      SPRING_PROFILES_ACTIVE: dev
