name: Deploy Angular application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./task-manager-client/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ./task-manager-client

      - name: Build
        run: npx nx run fuse:build:production -- --base-href "https://sanurb.github.io/task-manager/"
        working-directory: ./task-manager-client

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: angular-build
          path: dist/task-manager-client

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: angular-build
          path: dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/task-manager-client
